server {
    listen 80;
    server_name unk029.dev.openconsultinguk.com;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name unk029.dev.openconsultinguk.com;

    # Let's Encrypt SSL Certificate Paths
    ssl_certificate /etc/nginx/certs/live/unk029.dev.openconsultinguk.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/unk029.dev.openconsultinguk.com/privkey.pem;

    # SSL Security Enhancements
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Error Pages
    error_page 404 /index.html;

    # Don't cache HTML
    location ~* \.html?$ {
        add_header Cache-Control "public, max-age=0, must-revalidate";
    }

    # Don't cache JS
    location ~* \.js?$ {
        add_header Cache-Control "public, max-age=0, must-revalidate";
    }

    # Cache other assets
    location ~* \.(?:css|ico|woff|woff2|jpg|jpeg|png|gif|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}

